[theme]
base = "light"
primaryColor = "#7593af"
backgroundColor= "#7593af"
seconderyBackgroundColor = "#7593af"
textColor = "#0d0d0d"
borderColor = "#7593af"
font = "Edu NSW ACT Hand Cursive"
headingFont = "Edu NSW ACT Hand Cursive"

baseRadius = ""
[[theme.fontFaces]]
family = "Edu NSW ACT Hand Cursive"
url = "https://fonts.google.com/specimen/Edu+NSW+ACT+Cursive?preview.script=Latn&query=cursive"
weight = 400
style = "normal"
