[theme]
base = "light"
primaryColor = "#525e75"
backgroundColor= "#525e75"
seconderyBackgroundColor = "#525e75"
textColor = "#FFFFFF"
borderColor = "#525e75"
font = "Edu NSW ACT Hand Cursive"
headingFont = "Edu NSW ACT Hand Cursive"

baseRadius = ""
[[theme.fontFaces]]
family = "Edu NSW ACT Hand Cursive"
url = "https://fonts.google.com/specimen/Edu+NSW+ACT+Cursive?preview.script=Latn&query=cursive"
weight = 400
style = "normal"
